"""
SEPG — Selective Expert Proof Generation for zkFedMoE.

Each client generates a lightweight proof attesting to:
  - Which Top-K experts were selected
  - What DP parameters were applied (C, sigma, epsilon)
  - A SHA-256 hash of the sparse update for integrity

The server verifies proofs before including updates in aggregation.
"""

import hashlib
import io
import time
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

import torch


@dataclass
class SEPGProof:
    """Proof object generated by a client alongside its sparse update."""
    client_id: int
    round_id: int
    top_k_indices: List[int]
    dp_params: Dict[str, float]   # {"clip_norm": C, "noise_mult": sigma, "epsilon": eps}
    update_hash: str              # SHA-256 hex digest of the serialised update
    timestamp: float = field(default_factory=time.time)


def _hash_state(state: Dict[str, torch.Tensor]) -> str:
    """Compute SHA-256 hash of a state dict (deterministic serialisation)."""
    buf = io.BytesIO()
    # Sort keys for determinism
    for key in sorted(state.keys()):
        buf.write(key.encode("utf-8"))
        buf.write(state[key].cpu().float().numpy().tobytes())
    return hashlib.sha256(buf.getvalue()).hexdigest()


def generate_proof(
    client_id: int,
    round_id: int,
    top_k_indices: List[int],
    clip_norm: float,
    noise_multiplier: float,
    epsilon: float,
    sparse_state: Dict[str, torch.Tensor],
) -> SEPGProof:
    """Generate an SEPG proof for a client's sparse update."""
    return SEPGProof(
        client_id=client_id,
        round_id=round_id,
        top_k_indices=sorted(top_k_indices),
        dp_params={
            "clip_norm": clip_norm,
            "noise_mult": noise_multiplier,
            "epsilon": epsilon,
        },
        update_hash=_hash_state(sparse_state),
    )


def verify_proof(
    proof: SEPGProof,
    sparse_state: Dict[str, torch.Tensor],
    expected_k: int,
    max_clip_norm: float = 10.0,
    min_noise_mult: float = 0.01,
) -> Tuple[bool, str]:
    """
    Verify an SEPG proof.  Returns (passed: bool, reason: str).

    Checks:
      1. Top-K count matches expected K
      2. DP clip norm is within allowed bound
      3. Noise multiplier meets minimum threshold
      4. SHA-256 hash of update matches the proof
    """
    # Check 1: Top-K count
    if len(proof.top_k_indices) != expected_k:
        return False, f"top_k count {len(proof.top_k_indices)} != expected {expected_k}"

    # Check 2: Clip norm bound
    if proof.dp_params.get("clip_norm", float("inf")) > max_clip_norm:
        return False, f"clip_norm {proof.dp_params['clip_norm']} > max {max_clip_norm}"

    # Check 3: Minimum noise
    if proof.dp_params.get("noise_mult", 0) < min_noise_mult:
        return False, f"noise_mult {proof.dp_params['noise_mult']} < min {min_noise_mult}"

    # Check 4: Hash integrity
    computed_hash = _hash_state(sparse_state)
    if computed_hash != proof.update_hash:
        return False, "hash mismatch — update was tampered with"

    return True, "all checks passed"
